version: 2
jobs:
    build:
        working_directory: /work
        docker:
            - image: docker:18.02.0-ce-git
        context: org-global
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            - run: docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
            - run: docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
